type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Track @table {
  title: String!
  artistName: String!
  createdAt: Timestamp!
  albumTitle: String
  releaseYear: Int
  genres: [String]
  durationSeconds: Int
  externalId: String
}

type ListenLog @table {
  user: User!
  track: Track!
  listenDate: Timestamp!
  createdAt: Timestamp!
  context: String
  notes: String
}

type Review @table {
  user: User!
  track: Track!
  rating: Int!
  isPublic: Boolean!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  textReview: String
}

type Playlist @table {
  user: User!
  name: String!
  isPublic: Boolean!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  description: String
}

type PlaylistTrack @table(key: ["playlist", "track"]) {
  playlist: Playlist!
  track: Track!
  position: Int!
  addedAt: Timestamp!
  notes: String
}