type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Album @table {
  title: String!
  artistName: String!
  releaseYear: Int!
  createdAt: Timestamp!
  genre: String
  coverArtUrl: String
  summary: String
}

type Track @table {
  title: String!
  artistName: String!
  duration: Int!
  releaseYear: Int!
  createdAt: Timestamp!
  genre: String
  albumTitle: String
  album: Album
  externalId: String
}

type ListenEvent @table {
  user: User!
  track: Track!
  listenDate: Timestamp!
  createdAt: Timestamp!
  location: String
}

type Review @table {
  user: User!
  track: Track!
  rating: Int!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  isPublic: Boolean!
  reviewText: String
}

type Playlist @table {
  user: User!
  name: String!
  isPublic: Boolean!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  description: String
}

type PlaylistTrack @table(key: ["playlist", "track"]) {
  playlist: Playlist!
  track: Track!
  position: Int!
  note: String
}